/*
 * Example API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type NewEndpointPost201Response struct {

	Id int32 `json:"id,omitempty"`
}
